### ISSUE TITLE
Make geometry test

### ISSUE THREAD

**Issue by amfox37** [JCSDA-internal/ucldas#1]
## Description

Need to a ctest to ensure that UCLDAS geometry is working correctly

**Comment by gibbsp** [comment]
@amfox37 no progress since May21. Estimate is only 5. Please update status.

**Comment by amfox37** [comment]
@zhichang-guo has completed this, and a lot [more](https://github.com/JCSDA-internal/ucldas/tree/develop/test). But has not been operating within the JCSDA gitflow framework. Will again encourage him to work with us more fully as it's to everyone's benefit.
